### PR TITLE
Like button interaction implemented

### PR DESCRIPTION
**Pull request by JM066**
# Description
Just added the ternary operator to display liked when like button was previously clicked. 
## Type of change

Please delete options that are not relevant.

- [] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Showcase

Please attach a picture or a video showing what this change does.

https://user-images.githubusercontent.com/56789447/156921769-b78cb507-4060-43f1-a65b-394ce5ecc1c0.mp4

https://user-images.githubusercontent.com/56789447/158213677-79071c35-f3bd-49bc-8ca7-99a01b980741.mp4

### CODE REVIEW

**Comment by ivanms1** [comment]
Task linked: [CU-2az22d7 Make "Like" button interactions work on project page](https://app.clickup.com/t/2az22d7)

**Comment by ivanms1** [comment]
video or picture please :)

**Comment by ivanms1** [comment]
Looks good, but I think we need to reflect in the UI the user like action or if the user has already liked the project, maybe the button can be pink and say `Liked`, feel free to choose whatever you feel fit.

**Comment by JM066** [comment]
> Looks good, but I think we need to reflect in the UI the user like action or if the user has already liked the project, maybe the button can be pink and say `Liked`, feel free to choose whatever you feel fit.

**Review by ivanms1 — APPROVED** [review]
LGTM

**Pull request merged**
